"""Vaultwarden 1.37.3 API route catalog — committed source of truth as data.

Source: Vaultwarden 1.37.3 ``src/api/**`` Rocket route attributes.

Excluded (not agent API operations): the web-vault static/HTML hosting
domain, the WebSocket notifications hub, SSO browser callbacks (any path
containing ``oidc-signin`` or ``connect/authorize``), the ``/identity/connect/
token`` ``login`` handler (the base class owns authentication), and the
admin HTML page renders (``admin_disabled``, ``admin_page``,
``admin_page_login``, ``post_admin_login``, ``logout``, ``users_overview``,
``organizations_overview``, ``diagnostics``). Every JSON admin operation is
kept.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Route:
    """One Vaultwarden HTTP operation, normalized from a Rocket route attribute."""

    name: str
    domain: str
    http_method: str
    path: str
    auth: str
    path_params: tuple[str, ...] = ()
    query_params: tuple[str, ...] = ()
    catch_all: tuple[str, ...] = ()
    summary: str = ""
    destructive: bool = False


ROUTES: tuple[Route, ...] = (
    Route(
        name="post_set_password",
        domain="accounts",
        http_method="POST",
        path="api/accounts/set-password",
        auth="user",
        summary="Set initial master password (post-SSO/key-connector account provisioning)",
    ),
    Route(
        name="profile",
        domain="accounts",
        http_method="GET",
        path="api/accounts/profile",
        auth="user",
        summary="Get own user profile (email, name, org memberships, premium status)",
    ),
    Route(
        name="put_profile",
        domain="accounts",
        http_method="PUT",
        path="api/accounts/profile",
        auth="user",
        summary="Update profile fields (name, avatar color)",
    ),
    Route(
        name="post_profile",
        domain="accounts",
        http_method="POST",
        path="api/accounts/profile",
        auth="user",
        summary="Update profile fields (legacy POST alias of PUT)",
    ),
    Route(
        name="put_avatar",
        domain="accounts",
        http_method="PUT",
        path="api/accounts/avatar",
        auth="user",
        summary="Set avatar color",
    ),
    Route(
        name="get_public_keys",
        domain="accounts",
        http_method="GET",
        path="api/users/{user_id}/public-key",
        auth="user",
        path_params=("user_id",),
        summary="Get another user public RSA key by user id",
    ),
    Route(
        name="post_keys",
        domain="accounts",
        http_method="POST",
        path="api/accounts/keys",
        auth="user",
        summary="Upload/set the user RSA keypair (encrypted private key + public key)",
    ),
    Route(
        name="post_password",
        domain="accounts",
        http_method="POST",
        path="api/accounts/password",
        auth="user",
        summary="Change master password",
    ),
    Route(
        name="post_kdf",
        domain="accounts",
        http_method="POST",
        path="api/accounts/kdf",
        auth="user",
        summary="Change KDF algorithm/parameters (PBKDF2↔Argon2id, iterations, memory, parallelism)",
    ),
    Route(
        name="post_rotatekey",
        domain="accounts",
        http_method="POST",
        path="api/accounts/key-management/rotate-user-account-keys",
        auth="user",
        summary="Full account key rotation: re-encrypt user key, private key, and every cipher/folder/send key",
        destructive=True,
    ),
    Route(
        name="post_sstamp",
        domain="accounts",
        http_method="POST",
        path="api/accounts/security-stamp",
        auth="user",
        summary="Rotate security stamp (invalidates all other sessions/JWTs)",
    ),
    Route(
        name="post_email_token",
        domain="accounts",
        http_method="POST",
        path="api/accounts/email-token",
        auth="user",
        summary="Request email-change verification token (send code to new address)",
    ),
    Route(
        name="post_email",
        domain="accounts",
        http_method="POST",
        path="api/accounts/email",
        auth="user",
        summary="Confirm email change with token + new encrypted keys",
    ),
    Route(
        name="post_verify_email",
        domain="accounts",
        http_method="POST",
        path="api/accounts/verify-email",
        auth="user",
        summary="Request email verification (resend verify link) for current email",
    ),
    Route(
        name="post_verify_email_token",
        domain="accounts",
        http_method="POST",
        path="api/accounts/verify-email-token",
        auth="none",
        summary="Verify current email address ownership via emailed token",
    ),
    Route(
        name="post_delete_recover",
        domain="accounts",
        http_method="POST",
        path="api/accounts/delete-recover",
        auth="none",
        summary="Request account-deletion email (forgot-password-style deletion init)",
        destructive=True,
    ),
    Route(
        name="post_delete_recover_token",
        domain="accounts",
        http_method="POST",
        path="api/accounts/delete-recover-token",
        auth="none",
        summary="Complete account deletion using emailed token",
        destructive=True,
    ),
    Route(
        name="post_delete_account",
        domain="accounts",
        http_method="POST",
        path="api/accounts/delete",
        auth="user",
        summary="Delete own account (password/OTP confirmation in body)",
        destructive=True,
    ),
    Route(
        name="delete_account",
        domain="accounts",
        http_method="DELETE",
        path="api/accounts",
        auth="user",
        summary="Delete own account (REST DELETE alias)",
        destructive=True,
    ),
    Route(
        name="revision_date",
        domain="accounts",
        http_method="GET",
        path="api/accounts/revision-date",
        auth="user",
        summary="Get last vault revision timestamp (used by clients to decide whether to sync)",
    ),
    Route(
        name="password_hint",
        domain="accounts",
        http_method="POST",
        path="api/accounts/password-hint",
        auth="none",
        summary="Request password hint be emailed",
    ),
    Route(
        name="accounts_post_prelogin",
        domain="accounts",
        http_method="POST",
        path="api/accounts/prelogin",
        auth="none",
        summary="Get KDF type/iterations for an email before login (also mounted at /identity/accounts/prelogin)",
    ),
    Route(
        name="verify_password",
        domain="accounts",
        http_method="POST",
        path="api/accounts/verify-password",
        auth="user",
        summary="Verify current master password hash (used before sensitive UI actions)",
    ),
    Route(
        name="accounts_post_api_key",
        domain="accounts",
        http_method="POST",
        path="api/accounts/api-key",
        auth="user",
        summary="Generate/rotate the personal API key (client_credentials login secret)",
    ),
    Route(
        name="accounts_rotate_api_key",
        domain="accounts",
        http_method="POST",
        path="api/accounts/rotate-api-key",
        auth="user",
        summary="Rotate the personal API key",
        destructive=True,
    ),
    Route(
        name="get_known_device",
        domain="accounts",
        http_method="GET",
        path="api/devices/knowndevice",
        auth="none",
        summary="Check whether a device identifier is already known for an email",
    ),
    Route(
        name="get_all_devices",
        domain="accounts",
        http_method="GET",
        path="api/devices",
        auth="user",
        summary="List current user devices",
    ),
    Route(
        name="get_device",
        domain="accounts",
        http_method="GET",
        path="api/devices/identifier/{device_id}",
        auth="user",
        path_params=("device_id",),
        summary="Get one device by identifier",
    ),
    Route(
        name="post_device_token",
        domain="accounts",
        http_method="POST",
        path="api/devices/identifier/{device_id}/token",
        auth="user",
        path_params=("device_id",),
        summary="Set/update device push token",
    ),
    Route(
        name="put_device_token",
        domain="accounts",
        http_method="PUT",
        path="api/devices/identifier/{device_id}/token",
        auth="user",
        path_params=("device_id",),
        summary="Set/update device push token (PUT alias)",
    ),
    Route(
        name="put_clear_device_token",
        domain="accounts",
        http_method="PUT",
        path="api/devices/identifier/{device_id}/clear-token",
        auth="none",
        path_params=("device_id",),
        summary="Clear a device push token (public, used by push relay callbacks)",
    ),
    Route(
        name="post_clear_device_token",
        domain="accounts",
        http_method="POST",
        path="api/devices/identifier/{device_id}/clear-token",
        auth="none",
        path_params=("device_id",),
        summary="Clear a device push token (POST alias)",
    ),
    Route(
        name="get_tasks",
        domain="accounts",
        http_method="GET",
        path="api/tasks",
        auth="none",
        summary="List pending security tasks (at-risk password / admin-assigned tasks) for the current device",
    ),
    Route(
        name="post_auth_request",
        domain="accounts",
        http_method="POST",
        path="api/auth-requests",
        auth="none",
        summary='Create a new device "login with device" auth request',
    ),
    Route(
        name="get_auth_request",
        domain="accounts",
        http_method="GET",
        path="api/auth-requests/{auth_request_id}",
        auth="user",
        path_params=("auth_request_id",),
        summary="Poll status of one auth request by id",
    ),
    Route(
        name="put_auth_request",
        domain="accounts",
        http_method="PUT",
        path="api/auth-requests/{auth_request_id}",
        auth="user",
        path_params=("auth_request_id",),
        summary="Approve/deny an auth request from an already-approved device",
    ),
    Route(
        name="get_auth_request_response",
        domain="accounts",
        http_method="GET",
        path="api/auth-requests/{auth_request_id}/response",
        auth="none",
        path_params=("auth_request_id",),
        query_params=("code",),
        summary="Anonymous poll for approval + encrypted key once approved",
    ),
    Route(
        name="get_auth_requests",
        domain="accounts",
        http_method="GET",
        path="api/auth-requests",
        auth="user",
        summary="List all pending/approved auth requests for current user",
    ),
    Route(
        name="get_auth_requests_pending",
        domain="accounts",
        http_method="GET",
        path="api/auth-requests/pending",
        auth="user",
        summary="List only pending auth requests",
    ),
    Route(
        name="sync",
        domain="ciphers",
        http_method="GET",
        path="api/sync",
        auth="user",
        query_params=("data",),
        summary="Full vault sync: ciphers, folders, collections, sends, org/policy/domain metadata in one payload",
    ),
    Route(
        name="get_ciphers",
        domain="ciphers",
        http_method="GET",
        path="api/ciphers",
        auth="user",
        summary="List all ciphers owned by or shared with the user",
    ),
    Route(
        name="get_cipher",
        domain="ciphers",
        http_method="GET",
        path="api/ciphers/{cipher_id}",
        auth="user",
        path_params=("cipher_id",),
        summary="Get one cipher by id",
    ),
    Route(
        name="get_cipher_admin",
        domain="ciphers",
        http_method="GET",
        path="api/ciphers/{cipher_id}/admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Get one cipher with admin-view fields (org admin bypassing normal access)",
    ),
    Route(
        name="get_cipher_details",
        domain="ciphers",
        http_method="GET",
        path="api/ciphers/{cipher_id}/details",
        auth="user",
        path_params=("cipher_id",),
        summary="Get one cipher with full details incl. collection ids",
    ),
    Route(
        name="post_ciphers_admin",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/admin",
        auth="user",
        summary="Create a cipher as an org admin on behalf of the org (unassigned/admin path)",
    ),
    Route(
        name="post_ciphers_create",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/create",
        auth="user",
        summary="Create a cipher, optionally assigning collections in the same call",
    ),
    Route(
        name="post_ciphers",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers",
        auth="user",
        summary="Create a cipher (personal or org, no collections in this call)",
    ),
    Route(
        name="post_ciphers_import",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/import",
        auth="user",
        summary="Bulk import ciphers + folders in one call",
    ),
    Route(
        name="put_cipher_admin",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Update a cipher via the admin path",
    ),
    Route(
        name="post_cipher_admin",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Update a cipher via the admin path (POST alias)",
    ),
    Route(
        name="post_cipher",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}",
        auth="user",
        path_params=("cipher_id",),
        summary="Update a cipher",
    ),
    Route(
        name="put_cipher",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}",
        auth="user",
        path_params=("cipher_id",),
        summary="Update a cipher (PUT alias)",
    ),
    Route(
        name="post_cipher_partial",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/partial",
        auth="user",
        path_params=("cipher_id",),
        summary="Partial update: only folder assignment / favorite flag (no re-encryption needed)",
    ),
    Route(
        name="put_cipher_partial",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/partial",
        auth="user",
        path_params=("cipher_id",),
        summary="Partial update (PUT alias)",
    ),
    Route(
        name="put_collections2_update",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/collections_v2",
        auth="user",
        path_params=("cipher_id",),
        summary="Set the collections a cipher belongs to (v2, returns updated cipher)",
    ),
    Route(
        name="post_collections2_update",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/collections_v2",
        auth="user",
        path_params=("cipher_id",),
        summary="Set collections (v2, POST alias)",
    ),
    Route(
        name="put_collections_update",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/collections",
        auth="user",
        path_params=("cipher_id",),
        summary="Set the collections a cipher belongs to (legacy v1)",
    ),
    Route(
        name="post_collections_update",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/collections",
        auth="user",
        path_params=("cipher_id",),
        summary="Set collections (legacy v1, POST alias)",
    ),
    Route(
        name="put_collections_admin",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/collections-admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Set collections via admin path",
    ),
    Route(
        name="post_collections_admin",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/collections-admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Set collections via admin path (POST alias)",
    ),
    Route(
        name="post_cipher_share",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/share",
        auth="user",
        path_params=("cipher_id",),
        summary='Move a personal cipher into an organization ("share")',
    ),
    Route(
        name="put_cipher_share",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/share",
        auth="user",
        path_params=("cipher_id",),
        summary="Share a cipher (PUT alias)",
    ),
    Route(
        name="put_cipher_share_selected",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/share",
        auth="user",
        summary="Bulk share multiple ciphers to an org",
    ),
    Route(
        name="get_attachment",
        domain="ciphers",
        http_method="GET",
        path="api/ciphers/{cipher_id}/attachment/{attachment_id}",
        auth="user",
        path_params=("cipher_id", "attachment_id"),
        summary="Get attachment metadata + a short-lived download URL",
    ),
    Route(
        name="post_attachment_v2",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/attachment/v2",
        auth="user",
        path_params=("cipher_id",),
        summary="Begin attachment upload (v2): register metadata, get upload URL",
    ),
    Route(
        name="post_attachment_v2_data",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/attachment/{attachment_id}",
        auth="user",
        path_params=("cipher_id", "attachment_id"),
        summary="Upload the encrypted attachment bytes (v2 second phase)",
    ),
    Route(
        name="post_attachment",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/attachment",
        auth="user",
        path_params=("cipher_id",),
        summary="Upload attachment (legacy single-phase)",
    ),
    Route(
        name="post_attachment_admin",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/attachment-admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Upload attachment via admin path",
    ),
    Route(
        name="post_attachment_share",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/attachment/{attachment_id}/share",
        auth="user",
        path_params=("cipher_id", "attachment_id"),
        summary="Re-key an attachment when its cipher is shared to an org",
    ),
    Route(
        name="delete_attachment_post_admin",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/attachment/{attachment_id}/delete-admin",
        auth="user",
        path_params=("cipher_id", "attachment_id"),
        summary="Delete an attachment (admin path, POST alias)",
        destructive=True,
    ),
    Route(
        name="delete_attachment_post",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/attachment/{attachment_id}/delete",
        auth="user",
        path_params=("cipher_id", "attachment_id"),
        summary="Delete an attachment (POST alias)",
        destructive=True,
    ),
    Route(
        name="delete_attachment",
        domain="ciphers",
        http_method="DELETE",
        path="api/ciphers/{cipher_id}/attachment/{attachment_id}",
        auth="user",
        path_params=("cipher_id", "attachment_id"),
        summary="Delete an attachment",
        destructive=True,
    ),
    Route(
        name="delete_attachment_admin",
        domain="ciphers",
        http_method="DELETE",
        path="api/ciphers/{cipher_id}/attachment/{attachment_id}/admin",
        auth="user",
        path_params=("cipher_id", "attachment_id"),
        summary="Delete an attachment (admin path)",
        destructive=True,
    ),
    Route(
        name="delete_cipher_post",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/delete",
        auth="user",
        path_params=("cipher_id",),
        summary="Permanently delete a cipher (POST alias)",
        destructive=True,
    ),
    Route(
        name="delete_cipher_post_admin",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/{cipher_id}/delete-admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Permanently delete a cipher via admin path",
        destructive=True,
    ),
    Route(
        name="delete_cipher_put",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/delete",
        auth="user",
        path_params=("cipher_id",),
        summary="Soft-delete (move to trash) a cipher",
        destructive=True,
    ),
    Route(
        name="delete_cipher_put_admin",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/delete-admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Soft-delete via admin path",
        destructive=True,
    ),
    Route(
        name="delete_cipher",
        domain="ciphers",
        http_method="DELETE",
        path="api/ciphers/{cipher_id}",
        auth="user",
        path_params=("cipher_id",),
        summary="Permanently delete a cipher (REST DELETE)",
        destructive=True,
    ),
    Route(
        name="delete_cipher_admin",
        domain="ciphers",
        http_method="DELETE",
        path="api/ciphers/{cipher_id}/admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Permanently delete via admin path (REST DELETE)",
        destructive=True,
    ),
    Route(
        name="delete_cipher_selected",
        domain="ciphers",
        http_method="DELETE",
        path="api/ciphers",
        auth="user",
        summary="Bulk permanently delete ciphers by id list",
        destructive=True,
    ),
    Route(
        name="delete_cipher_selected_post",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/delete",
        auth="user",
        summary="Bulk permanent delete (POST alias)",
        destructive=True,
    ),
    Route(
        name="delete_cipher_selected_put",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/delete",
        auth="user",
        summary="Bulk soft-delete (move to trash)",
        destructive=True,
    ),
    Route(
        name="delete_cipher_selected_admin",
        domain="ciphers",
        http_method="DELETE",
        path="api/ciphers/admin",
        auth="user",
        summary="Bulk permanent delete via admin path",
        destructive=True,
    ),
    Route(
        name="delete_cipher_selected_post_admin",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/delete-admin",
        auth="user",
        summary="Bulk permanent delete via admin path (POST alias)",
        destructive=True,
    ),
    Route(
        name="delete_cipher_selected_put_admin",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/delete-admin",
        auth="user",
        summary="Bulk soft-delete via admin path",
        destructive=True,
    ),
    Route(
        name="restore_cipher_put",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/restore",
        auth="user",
        path_params=("cipher_id",),
        summary="Restore one cipher from trash",
    ),
    Route(
        name="restore_cipher_put_admin",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/restore-admin",
        auth="user",
        path_params=("cipher_id",),
        summary="Restore one cipher from trash via admin path",
    ),
    Route(
        name="restore_cipher_selected_admin",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/restore-admin",
        auth="user",
        summary="Bulk restore from trash via admin path",
    ),
    Route(
        name="restore_cipher_selected",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/restore",
        auth="user",
        summary="Bulk restore from trash",
    ),
    Route(
        name="move_cipher_selected",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/move",
        auth="user",
        summary="Bulk move ciphers into a folder (or remove from folder)",
    ),
    Route(
        name="move_cipher_selected_put",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/move",
        auth="user",
        summary="Bulk move ciphers into a folder (PUT alias)",
    ),
    Route(
        name="purge_org_vault",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/purge",
        auth="user",
        query_params=("organization",),
        summary="Irreversibly delete ALL ciphers in an organization",
        destructive=True,
    ),
    Route(
        name="purge_personal_vault",
        domain="ciphers",
        http_method="POST",
        path="api/ciphers/purge",
        auth="user",
        summary="Irreversibly delete ALL of the caller’s personal ciphers (and folders)",
        destructive=True,
    ),
    Route(
        name="archive_cipher_put",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/archive",
        auth="user",
        path_params=("cipher_id",),
        summary="Archive one cipher (hide from default view, distinct from trash)",
    ),
    Route(
        name="archive_cipher_selected",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/archive",
        auth="user",
        summary="Bulk archive ciphers",
    ),
    Route(
        name="unarchive_cipher_put",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/{cipher_id}/unarchive",
        auth="user",
        path_params=("cipher_id",),
        summary="Unarchive one cipher",
    ),
    Route(
        name="unarchive_cipher_selected",
        domain="ciphers",
        http_method="PUT",
        path="api/ciphers/unarchive",
        auth="user",
        summary="Bulk unarchive ciphers",
    ),
    Route(
        name="get_folders",
        domain="folders",
        http_method="GET",
        path="api/folders",
        auth="user",
        summary="List all folders",
    ),
    Route(
        name="get_folder",
        domain="folders",
        http_method="GET",
        path="api/folders/{folder_id}",
        auth="user",
        path_params=("folder_id",),
        summary="Get one folder by id",
    ),
    Route(
        name="post_folders",
        domain="folders",
        http_method="POST",
        path="api/folders",
        auth="user",
        summary="Create a folder",
    ),
    Route(
        name="post_folder",
        domain="folders",
        http_method="POST",
        path="api/folders/{folder_id}",
        auth="user",
        path_params=("folder_id",),
        summary="Rename a folder (POST alias)",
    ),
    Route(
        name="put_folder",
        domain="folders",
        http_method="PUT",
        path="api/folders/{folder_id}",
        auth="user",
        path_params=("folder_id",),
        summary="Rename a folder",
    ),
    Route(
        name="delete_folder_post",
        domain="folders",
        http_method="POST",
        path="api/folders/{folder_id}/delete",
        auth="user",
        path_params=("folder_id",),
        summary="Delete a folder (POST alias)",
        destructive=True,
    ),
    Route(
        name="delete_folder",
        domain="folders",
        http_method="DELETE",
        path="api/folders/{folder_id}",
        auth="user",
        path_params=("folder_id",),
        summary="Delete a folder",
        destructive=True,
    ),
    Route(
        name="create_organization",
        domain="organizations",
        http_method="POST",
        path="api/organizations",
        auth="user",
        summary="Create a new organization",
    ),
    Route(
        name="organizations_delete_organization",
        domain="organizations",
        http_method="DELETE",
        path="api/organizations/{org_id}",
        auth="user",
        path_params=("org_id",),
        summary="Delete an organization",
        destructive=True,
    ),
    Route(
        name="post_delete_organization",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/delete",
        auth="user",
        path_params=("org_id",),
        summary="Delete an organization (POST alias)",
        destructive=True,
    ),
    Route(
        name="leave_organization",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/leave",
        auth="user",
        path_params=("org_id",),
        summary="Current user leaves an organization",
        destructive=True,
    ),
    Route(
        name="get_organization",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}",
        auth="user",
        path_params=("org_id",),
        summary="Get organization details",
    ),
    Route(
        name="put_organization",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}",
        auth="user",
        path_params=("org_id",),
        summary="Update organization settings (name, billing email, etc.)",
    ),
    Route(
        name="post_organization",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}",
        auth="user",
        path_params=("org_id",),
        summary="Update organization settings (POST alias)",
    ),
    Route(
        name="get_user_collections",
        domain="organizations",
        http_method="GET",
        path="api/collections",
        auth="user",
        summary="List collections the current user has access to (across all orgs)",
    ),
    Route(
        name="get_auto_enroll_status",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{identifier}/auto-enroll-status",
        auth="user",
        path_params=("identifier",),
        summary="Check whether org auto-enrolls new members into password-reset admin recovery",
    ),
    Route(
        name="get_org_collections",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/collections",
        auth="user",
        path_params=("org_id",),
        summary="List all collections in an org",
    ),
    Route(
        name="get_org_collections_details",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/collections/details",
        auth="user",
        path_params=("org_id",),
        summary="List collections with per-collection access details",
    ),
    Route(
        name="post_organization_collections",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/collections",
        auth="user",
        path_params=("org_id",),
        summary="Create a collection",
    ),
    Route(
        name="post_bulk_access_collections",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/collections/bulk-access",
        auth="user",
        path_params=("org_id",),
        summary="Bulk-set which users/groups can access a set of collections",
    ),
    Route(
        name="put_organization_collection_update",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/collections/{col_id}",
        auth="user",
        path_params=("org_id", "col_id"),
        summary="Update a collection (rename, reassign users/groups)",
    ),
    Route(
        name="post_organization_collection_update",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/collections/{col_id}",
        auth="user",
        path_params=("org_id", "col_id"),
        summary="Update a collection (POST alias)",
    ),
    Route(
        name="delete_organization_collection",
        domain="organizations",
        http_method="DELETE",
        path="api/organizations/{org_id}/collections/{col_id}",
        auth="user",
        path_params=("org_id", "col_id"),
        summary="Delete a collection",
        destructive=True,
    ),
    Route(
        name="post_organization_collection_delete",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/collections/{col_id}/delete",
        auth="user",
        path_params=("org_id", "col_id"),
        summary="Delete a collection (POST alias)",
        destructive=True,
    ),
    Route(
        name="bulk_delete_organization_collections",
        domain="organizations",
        http_method="DELETE",
        path="api/organizations/{org_id}/collections",
        auth="user",
        path_params=("org_id",),
        summary="Bulk delete collections by id",
        destructive=True,
    ),
    Route(
        name="get_org_collection_detail",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/collections/{col_id}/details",
        auth="user",
        path_params=("org_id", "col_id"),
        summary="Get one collection’s details",
    ),
    Route(
        name="get_collection_users",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/collections/{col_id}/users",
        auth="user",
        path_params=("org_id", "col_id"),
        summary="List users/groups with access to one collection",
    ),
    Route(
        name="get_org_details",
        domain="organizations",
        http_method="GET",
        path="api/ciphers/organization-details",
        auth="user",
        query_params=("data",),
        summary="Get org-scoped cipher listing with per-cipher collection membership",
    ),
    Route(
        name="get_org_domain_sso_verified",
        domain="organizations",
        http_method="POST",
        path="api/organizations/domain/sso/verified",
        auth="none",
        summary="Check whether an org’s SSO domain claim is verified",
    ),
    Route(
        name="get_members",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/users",
        auth="user",
        path_params=("org_id",),
        query_params=("data",),
        summary='List organization members ("users")',
    ),
    Route(
        name="post_org_keys",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/keys",
        auth="user",
        path_params=("org_id",),
        summary="Upload the organization’s RSA keypair at org-creation time",
    ),
    Route(
        name="organizations_send_invite",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/users/invite",
        auth="user",
        path_params=("org_id",),
        summary="Invite a user to the organization by email",
    ),
    Route(
        name="bulk_reinvite_members",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/users/reinvite",
        auth="user",
        path_params=("org_id",),
        summary="Bulk resend pending invites",
    ),
    Route(
        name="reinvite_member",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/users/{member_id}/reinvite",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Resend one pending invite",
    ),
    Route(
        name="organizations_accept_invite",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/users/{member_id}/accept",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Invited user accepts the org invite",
    ),
    Route(
        name="bulk_confirm_invite",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/users/confirm",
        auth="user",
        path_params=("org_id",),
        summary="Bulk confirm accepted invites, delivering the org key to each new member",
    ),
    Route(
        name="confirm_invite",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/users/{member_id}/confirm",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Confirm one accepted invite",
    ),
    Route(
        name="get_org_user_mini_details",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/users/mini-details",
        auth="user",
        path_params=("org_id",),
        summary="List members with minimal fields (id/name/email) for UI pickers",
    ),
    Route(
        name="get_user",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/users/{member_id}",
        auth="user",
        path_params=("org_id", "member_id"),
        query_params=("data",),
        summary="Get one member’s full details",
    ),
    Route(
        name="put_member",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/{member_id}",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Edit a member (role, collection access, groups)",
    ),
    Route(
        name="edit_member",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/users/{member_id}",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Edit a member (POST alias)",
    ),
    Route(
        name="bulk_delete_member",
        domain="organizations",
        http_method="DELETE",
        path="api/organizations/{org_id}/users",
        auth="user",
        path_params=("org_id",),
        summary="Bulk remove members from the org",
        destructive=True,
    ),
    Route(
        name="delete_member",
        domain="organizations",
        http_method="DELETE",
        path="api/organizations/{org_id}/users/{member_id}",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Remove one member from the org",
        destructive=True,
    ),
    Route(
        name="bulk_public_keys",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/users/public-keys",
        auth="user",
        path_params=("org_id",),
        summary="Bulk-fetch public keys for a list of user ids",
    ),
    Route(
        name="post_org_import",
        domain="organizations",
        http_method="POST",
        path="api/ciphers/import-organization",
        auth="user",
        query_params=("query",),
        summary="Bulk import ciphers directly into an organization (personal-vault-style import scoped to an org)",
    ),
    Route(
        name="post_bulk_collections",
        domain="organizations",
        http_method="POST",
        path="api/ciphers/bulk-collections",
        auth="user",
        summary="Bulk-assign a set of ciphers to collections",
    ),
    Route(
        name="list_policies",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/policies",
        auth="user",
        path_params=("org_id",),
        summary="List all policies configured for the org",
    ),
    Route(
        name="list_policies_token",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/policies/token",
        auth="none",
        path_params=("org_id",),
        query_params=("token",),
        summary="List policies visible to an not-yet-member using their invite token",
    ),
    Route(
        name="get_dummy_master_password_policy",
        domain="organizations",
        http_method="GET",
        path="api/organizations/00000000-01DC-01DC-01DC-000000000000/policies/master-password",
        auth="none",
        summary="Return an empty master-password-policy stub for a placeholder org id",
    ),
    Route(
        name="get_master_password_policy",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/policies/master-password",
        auth="user",
        path_params=("org_id",),
        summary="Get the effective master-password-complexity policy for the org",
    ),
    Route(
        name="get_policy",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/policies/{pol_type}",
        auth="user",
        path_params=("org_id", "pol_type"),
        summary="Get one policy by type",
    ),
    Route(
        name="put_policy",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/policies/{pol_type}",
        auth="user",
        path_params=("org_id", "pol_type"),
        summary="Update one policy by type",
    ),
    Route(
        name="put_policy_vnext",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/policies/{pol_type}/vnext",
        auth="user",
        path_params=("org_id", "pol_type"),
        summary="Update one policy by type (newer response shape)",
    ),
    Route(
        name="get_plans",
        domain="organizations",
        http_method="GET",
        path="api/plans",
        auth="none",
        summary="List available subscription plans",
    ),
    Route(
        name="get_billing_metadata",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{_org_id}/billing/metadata",
        auth="user",
        path_params=("_org_id",),
        summary="Get org billing metadata",
    ),
    Route(
        name="get_billing_warnings",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{_org_id}/billing/vnext/warnings",
        auth="user",
        path_params=("_org_id",),
        summary="Get org billing warning banners",
    ),
    Route(
        name="get_self_host_billing_metadata",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{_org_id}/billing/vnext/self-host/metadata",
        auth="user",
        path_params=("_org_id",),
        summary="Get self-host billing metadata",
    ),
    Route(
        name="revoke_member",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/{member_id}/revoke",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Revoke one member’s access without removing them (keeps external_id/history)",
        destructive=True,
    ),
    Route(
        name="bulk_revoke_members",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/revoke",
        auth="user",
        path_params=("org_id",),
        summary="Bulk revoke members",
        destructive=True,
    ),
    Route(
        name="restore_member_vnext",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/{member_id}/restore/vnext",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Restore a revoked member (newer response shape)",
    ),
    Route(
        name="restore_member",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/{member_id}/restore",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Restore a revoked member",
    ),
    Route(
        name="bulk_restore_members",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/restore",
        auth="user",
        path_params=("org_id",),
        summary="Bulk restore revoked members",
    ),
    Route(
        name="get_groups",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/groups",
        auth="user",
        path_params=("org_id",),
        summary="List org groups (collections of members for access assignment)",
    ),
    Route(
        name="get_groups_details",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/groups/details",
        auth="user",
        path_params=("org_id",),
        summary="List groups with member/collection details",
    ),
    Route(
        name="post_group",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/groups/{group_id}",
        auth="user",
        path_params=("org_id", "group_id"),
        summary="Update a group (POST alias, id in path)",
    ),
    Route(
        name="post_groups",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/groups",
        auth="user",
        path_params=("org_id",),
        summary="Create a group",
    ),
    Route(
        name="put_group",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/groups/{group_id}",
        auth="user",
        path_params=("org_id", "group_id"),
        summary="Update a group",
    ),
    Route(
        name="get_group_details",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/groups/{group_id}/details",
        auth="user",
        path_params=("org_id", "group_id"),
        summary="Get one group with members + collections",
    ),
    Route(
        name="post_delete_group",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/groups/{group_id}/delete",
        auth="user",
        path_params=("org_id", "group_id"),
        summary="Delete a group (POST alias)",
        destructive=True,
    ),
    Route(
        name="delete_group",
        domain="organizations",
        http_method="DELETE",
        path="api/organizations/{org_id}/groups/{group_id}",
        auth="user",
        path_params=("org_id", "group_id"),
        summary="Delete a group",
        destructive=True,
    ),
    Route(
        name="bulk_delete_groups",
        domain="organizations",
        http_method="DELETE",
        path="api/organizations/{org_id}/groups",
        auth="user",
        path_params=("org_id",),
        summary="Bulk delete groups",
        destructive=True,
    ),
    Route(
        name="get_group",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/groups/{group_id}",
        auth="user",
        path_params=("org_id", "group_id"),
        summary="Get one group",
    ),
    Route(
        name="get_group_members",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/groups/{group_id}/users",
        auth="user",
        path_params=("org_id", "group_id"),
        summary="List members of a group",
    ),
    Route(
        name="put_group_members",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/groups/{group_id}/users",
        auth="user",
        path_params=("org_id", "group_id"),
        summary="Set which members belong to a group",
    ),
    Route(
        name="post_delete_group_member",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/groups/{group_id}/delete-user/{member_id}",
        auth="user",
        path_params=("org_id", "group_id", "member_id"),
        summary="Remove one member from a group",
        destructive=True,
    ),
    Route(
        name="get_organization_public_key",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/public-key",
        auth="user",
        path_params=("org_id",),
        summary="Get the org’s public RSA key",
    ),
    Route(
        name="get_organization_keys",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/keys",
        auth="user",
        path_params=("org_id",),
        summary="Get the org’s public key + (if authorized) encrypted private key",
    ),
    Route(
        name="put_recover_account",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/{member_id}/recover-account",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Admin completes account-recovery: submits a brand-new master key for a member using the org-held reset_password_key",
    ),
    Route(
        name="put_reset_password",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/{member_id}/reset-password",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Alias/step of admin-initiated password reset",
        destructive=True,
    ),
    Route(
        name="get_reset_password_details",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/users/{member_id}/reset-password-details",
        auth="user",
        path_params=("org_id", "member_id"),
        summary="Get the data needed to perform admin password reset for a member (their reset_password_key + KDF settings)",
    ),
    Route(
        name="put_reset_password_enrollment",
        domain="organizations",
        http_method="PUT",
        path="api/organizations/{org_id}/users/{user_id}/reset-password-enrollment",
        auth="user",
        path_params=("org_id", "user_id"),
        summary="Member opts in/out of admin password-reset recovery",
        destructive=True,
    ),
    Route(
        name="get_org_export",
        domain="organizations",
        http_method="GET",
        path="api/organizations/{org_id}/export",
        auth="user",
        path_params=("org_id",),
        summary="Export all org cipher data (admin-triggered org vault export)",
    ),
    Route(
        name="organizations_post_api_key",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/api-key",
        auth="user",
        path_params=("org_id",),
        summary="Generate/rotate the org’s API key (for client_credentials / public API access)",
    ),
    Route(
        name="organizations_rotate_api_key",
        domain="organizations",
        http_method="POST",
        path="api/organizations/{org_id}/rotate-api-key",
        auth="user",
        path_params=("org_id",),
        summary="Rotate the org’s API key",
        destructive=True,
    ),
    Route(
        name="get_sends",
        domain="sends",
        http_method="GET",
        path="api/sends",
        auth="user",
        summary="List the caller’s own Sends",
    ),
    Route(
        name="get_send",
        domain="sends",
        http_method="GET",
        path="api/sends/{send_id}",
        auth="user",
        path_params=("send_id",),
        summary="Get one of the caller’s own Sends by id",
    ),
    Route(
        name="post_send",
        domain="sends",
        http_method="POST",
        path="api/sends",
        auth="user",
        summary="Create a text-type (or metadata-only) Send",
    ),
    Route(
        name="post_send_file",
        domain="sends",
        http_method="POST",
        path="api/sends/file",
        auth="user",
        summary="Create a file-type Send (legacy single-phase upload)",
    ),
    Route(
        name="post_send_file_v2",
        domain="sends",
        http_method="POST",
        path="api/sends/file/v2",
        auth="user",
        summary="Begin a file-type Send (v2): register metadata, get upload URL",
    ),
    Route(
        name="post_send_file_v2_data",
        domain="sends",
        http_method="POST",
        path="api/sends/{send_id}/file/{file_id}",
        auth="user",
        path_params=("send_id", "file_id"),
        summary="Upload the encrypted Send file bytes (v2 second phase)",
    ),
    Route(
        name="post_access",
        domain="sends",
        http_method="POST",
        path="api/sends/access",
        auth="none",
        summary="Anonymous: fetch a Send’s metadata by access id (for viewing/decrypting)",
    ),
    Route(
        name="post_access_legacy",
        domain="sends",
        http_method="POST",
        path="api/sends/access/{access_id}",
        auth="none",
        path_params=("access_id",),
        summary="Anonymous: legacy path for fetching a Send by access id",
    ),
    Route(
        name="post_access_file",
        domain="sends",
        http_method="POST",
        path="api/sends/access/file/{file_id}",
        auth="none",
        path_params=("file_id",),
        summary="Anonymous: get a download URL for a Send file",
    ),
    Route(
        name="post_access_file_legacy",
        domain="sends",
        http_method="POST",
        path="api/sends/{send_id}/access/file/{file_id}",
        auth="none",
        path_params=("send_id", "file_id"),
        summary="Anonymous: legacy get-download-URL path",
    ),
    Route(
        name="download_send",
        domain="sends",
        http_method="GET",
        path="api/sends/{send_id}/{file_id}",
        auth="none",
        path_params=("send_id", "file_id"),
        query_params=("t",),
        summary="Anonymous: download the actual (still-encrypted) Send file bytes",
    ),
    Route(
        name="put_send",
        domain="sends",
        http_method="PUT",
        path="api/sends/{send_id}",
        auth="user",
        path_params=("send_id",),
        summary="Update a Send (name/notes/text/expiry/password/max access count)",
    ),
    Route(
        name="delete_send",
        domain="sends",
        http_method="DELETE",
        path="api/sends/{send_id}",
        auth="user",
        path_params=("send_id",),
        summary="Delete a Send",
        destructive=True,
    ),
    Route(
        name="put_remove_password",
        domain="sends",
        http_method="PUT",
        path="api/sends/{send_id}/remove-password",
        auth="user",
        path_params=("send_id",),
        summary="Remove the password requirement from a Send",
        destructive=True,
    ),
    Route(
        name="get_contacts",
        domain="emergency_access",
        http_method="GET",
        path="api/emergency-access/trusted",
        auth="user",
        summary="List people the caller has granted emergency access to (as grantor)",
    ),
    Route(
        name="get_grantees",
        domain="emergency_access",
        http_method="GET",
        path="api/emergency-access/granted",
        auth="user",
        summary="List people who have granted the caller emergency access (as grantee)",
    ),
    Route(
        name="get_emergency_access",
        domain="emergency_access",
        http_method="GET",
        path="api/emergency-access/{emer_id}",
        auth="user",
        path_params=("emer_id",),
        summary="Get one emergency-access record by id",
    ),
    Route(
        name="put_emergency_access",
        domain="emergency_access",
        http_method="PUT",
        path="api/emergency-access/{emer_id}",
        auth="user",
        path_params=("emer_id",),
        summary="Update wait-time/type of an emergency-access grant",
    ),
    Route(
        name="post_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}",
        auth="user",
        path_params=("emer_id",),
        summary="Update an emergency-access grant (POST alias)",
    ),
    Route(
        name="delete_emergency_access",
        domain="emergency_access",
        http_method="DELETE",
        path="api/emergency-access/{emer_id}",
        auth="user",
        path_params=("emer_id",),
        summary="Delete/revoke an emergency-access relationship",
        destructive=True,
    ),
    Route(
        name="post_delete_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/delete",
        auth="user",
        path_params=("emer_id",),
        summary="Delete/revoke (POST alias)",
        destructive=True,
    ),
    Route(
        name="emergency_access_send_invite",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/invite",
        auth="user",
        summary="Grantor invites another user (by email) as emergency contact",
    ),
    Route(
        name="resend_invite",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/reinvite",
        auth="user",
        path_params=("emer_id",),
        summary="Grantor resends a pending emergency-access invite",
    ),
    Route(
        name="emergency_access_accept_invite",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/accept",
        auth="user",
        path_params=("emer_id",),
        summary="Grantee accepts a pending emergency-access invite",
    ),
    Route(
        name="confirm_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/confirm",
        auth="user",
        path_params=("emer_id",),
        summary="Grantor confirms the grantee, delivering the grantor’s vault key encrypted for the grantee",
    ),
    Route(
        name="initiate_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/initiate",
        auth="user",
        path_params=("emer_id",),
        summary="Grantee starts the takeover/view waiting period",
    ),
    Route(
        name="approve_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/approve",
        auth="user",
        path_params=("emer_id",),
        summary="Grantor approves an in-progress request early (skips wait)",
    ),
    Route(
        name="reject_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/reject",
        auth="user",
        path_params=("emer_id",),
        summary="Grantor rejects/cancels an in-progress request",
        destructive=True,
    ),
    Route(
        name="view_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/view",
        auth="user",
        path_params=("emer_id",),
        summary="Grantee views the grantor’s vault (read-only) after approval/wait elapses",
    ),
    Route(
        name="takeover_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/takeover",
        auth="user",
        path_params=("emer_id",),
        summary="Grantee begins password takeover: server returns grantor’s KDF settings + encrypted key",
        destructive=True,
    ),
    Route(
        name="password_emergency_access",
        domain="emergency_access",
        http_method="POST",
        path="api/emergency-access/{emer_id}/password",
        auth="user",
        path_params=("emer_id",),
        summary="Grantee completes takeover: uploads the grantor’s user key re-encrypted under a NEW master key/password chosen by the grantee",
    ),
    Route(
        name="policies_emergency_access",
        domain="emergency_access",
        http_method="GET",
        path="api/emergency-access/{emer_id}/policies",
        auth="user",
        path_params=("emer_id",),
        summary="Get org policies applicable to the emergency-access relationship",
    ),
    Route(
        name="generate_authenticator",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/get-authenticator",
        auth="user",
        summary="Generate a new TOTP secret + provisioning QR data",
    ),
    Route(
        name="activate_authenticator",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/authenticator",
        auth="user",
        summary="Enable TOTP 2FA by confirming a generated code",
    ),
    Route(
        name="activate_authenticator_put",
        domain="two_factor",
        http_method="PUT",
        path="api/two-factor/authenticator",
        auth="user",
        summary="Enable TOTP 2FA (PUT alias)",
    ),
    Route(
        name="disable_authenticator",
        domain="two_factor",
        http_method="DELETE",
        path="api/two-factor/authenticator",
        auth="user",
        summary="Disable TOTP 2FA",
        destructive=True,
    ),
    Route(
        name="get_duo",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/get-duo",
        auth="user",
        summary="Get current Duo 2FA configuration (masked)",
    ),
    Route(
        name="activate_duo",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/duo",
        auth="user",
        summary="Enable/update Duo (or Duo OIDC) 2FA",
    ),
    Route(
        name="activate_duo_put",
        domain="two_factor",
        http_method="PUT",
        path="api/two-factor/duo",
        auth="user",
        summary="Enable/update Duo 2FA (PUT alias)",
    ),
    Route(
        name="send_email_login",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/send-email-login",
        auth="none",
        summary="Send the 2FA email code during login (pre-auth, device-scoped)",
    ),
    Route(
        name="get_email",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/get-email",
        auth="user",
        summary="Check whether email 2FA is set up / request setup email",
    ),
    Route(
        name="send_email",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/send-email",
        auth="user",
        summary="Send/resend the email-2FA setup verification code",
    ),
    Route(
        name="email",
        domain="two_factor",
        http_method="PUT",
        path="api/two-factor/email",
        auth="user",
        summary="Confirm email-2FA setup with the emailed code",
    ),
    Route(
        name="get_twofactor",
        domain="two_factor",
        http_method="GET",
        path="api/two-factor",
        auth="user",
        summary="List enabled 2FA methods for the user",
    ),
    Route(
        name="get_recover",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/get-recover",
        auth="user",
        summary="Get the 2FA recovery code (used if all 2FA devices are lost)",
    ),
    Route(
        name="disable_twofactor",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/disable",
        auth="user",
        summary="Disable a specific 2FA provider",
        destructive=True,
    ),
    Route(
        name="disable_twofactor_put",
        domain="two_factor",
        http_method="PUT",
        path="api/two-factor/disable",
        auth="user",
        summary="Disable a specific 2FA provider (PUT alias)",
        destructive=True,
    ),
    Route(
        name="get_device_verification_settings",
        domain="two_factor",
        http_method="GET",
        path="api/two-factor/get-device-verification-settings",
        auth="user",
        summary="Get/return device-verification (new-device email) settings",
    ),
    Route(
        name="request_otp",
        domain="two_factor",
        http_method="POST",
        path="api/accounts/request-otp",
        auth="user",
        summary="Request an OTP (emailed) to re-verify identity before a sensitive action",
    ),
    Route(
        name="verify_otp",
        domain="two_factor",
        http_method="POST",
        path="api/accounts/verify-otp",
        auth="user",
        summary="Verify the OTP from request_otp",
    ),
    Route(
        name="get_webauthn",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/get-webauthn",
        auth="user",
        summary="List registered WebAuthn/FIDO2 2FA security keys",
    ),
    Route(
        name="generate_webauthn_challenge",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/get-webauthn-challenge",
        auth="user",
        summary="Generate a WebAuthn registration challenge",
    ),
    Route(
        name="activate_webauthn",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/webauthn",
        auth="user",
        summary="Register a new WebAuthn security key for 2FA",
    ),
    Route(
        name="activate_webauthn_put",
        domain="two_factor",
        http_method="PUT",
        path="api/two-factor/webauthn",
        auth="user",
        summary="Register a WebAuthn key (PUT alias)",
    ),
    Route(
        name="delete_webauthn",
        domain="two_factor",
        http_method="DELETE",
        path="api/two-factor/webauthn",
        auth="user",
        summary="Remove a registered WebAuthn security key",
        destructive=True,
    ),
    Route(
        name="generate_yubikey",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/get-yubikey",
        auth="user",
        summary="Get current YubiKey OTP 2FA configuration (masked)",
    ),
    Route(
        name="activate_yubikey",
        domain="two_factor",
        http_method="POST",
        path="api/two-factor/yubikey",
        auth="user",
        summary="Enable YubiKey OTP 2FA",
    ),
    Route(
        name="activate_yubikey_put",
        domain="two_factor",
        http_method="PUT",
        path="api/two-factor/yubikey",
        auth="user",
        summary="Enable YubiKey OTP 2FA (PUT alias)",
    ),
    Route(
        name="get_org_events",
        domain="events",
        http_method="GET",
        path="api/organizations/{org_id}/events",
        auth="user",
        path_params=("org_id",),
        query_params=("data",),
        summary="List audit-log events for an organization",
    ),
    Route(
        name="get_cipher_events",
        domain="events",
        http_method="GET",
        path="api/ciphers/{cipher_id}/events",
        auth="user",
        path_params=("cipher_id",),
        query_params=("data",),
        summary="List audit-log events for one cipher",
    ),
    Route(
        name="get_user_events",
        domain="events",
        http_method="GET",
        path="api/organizations/{org_id}/users/{member_id}/events",
        auth="user",
        path_params=("org_id", "member_id"),
        query_params=("data",),
        summary="List audit-log events for one org member",
    ),
    Route(
        name="post_events_collect",
        domain="events",
        http_method="POST",
        path="events/collect",
        auth="user",
        summary="Client-side telemetry/event ingestion endpoint used by web-vault to batch-report UI events",
    ),
    Route(
        name="identity_post_prelogin",
        domain="identity",
        http_method="POST",
        path="identity/accounts/prelogin",
        auth="none",
        summary="Get a user’s KDF type/iterations/memory/parallelism by email before attempting login",
    ),
    Route(
        name="prelogin_password",
        domain="identity",
        http_method="POST",
        path="identity/accounts/prelogin/password",
        auth="none",
        summary="Variant prelogin returning the newer MasterPasswordUnlockData shape",
    ),
    Route(
        name="identity_register",
        domain="identity",
        http_method="POST",
        path="identity/accounts/register",
        auth="none",
        summary="Register a new account (email, name, master-password hash, encrypted keys, KDF params)",
    ),
    Route(
        name="register_verification_email",
        domain="identity",
        http_method="POST",
        path="identity/accounts/register/send-verification-email",
        auth="none",
        summary="Send the registration email-verification code",
    ),
    Route(
        name="register_finish",
        domain="identity",
        http_method="POST",
        path="identity/accounts/register/finish",
        auth="none",
        summary="Finish registration after email verification (submits the same keyset payload as identity_register)",
    ),
    Route(
        name="prevalidate",
        domain="identity",
        http_method="GET",
        path="identity/sso/prevalidate",
        auth="none",
        summary="Pre-validate an SSO organization identifier before redirecting to the IdP",
    ),
    Route(
        name="invite_user",
        domain="admin",
        http_method="POST",
        path="admin/invite",
        auth="admin",
        summary="Create/invite a new instance user from the admin panel",
    ),
    Route(
        name="test_smtp",
        domain="admin",
        http_method="POST",
        path="admin/test/smtp",
        auth="admin",
        summary="Send a test email to verify SMTP configuration",
    ),
    Route(
        name="get_users_json",
        domain="admin",
        http_method="GET",
        path="admin/users",
        auth="admin",
        summary="List all instance users (JSON, for the admin table)",
    ),
    Route(
        name="get_user_by_mail_json",
        domain="admin",
        http_method="GET",
        path="admin/users/by-mail/{mail}",
        auth="admin",
        path_params=("mail",),
        summary="Look up one instance user by email",
    ),
    Route(
        name="get_user_json",
        domain="admin",
        http_method="GET",
        path="admin/users/{user_id}",
        auth="admin",
        path_params=("user_id",),
        summary="Get one instance user by id",
    ),
    Route(
        name="delete_user",
        domain="admin",
        http_method="POST",
        path="admin/users/{user_id}/delete",
        auth="admin",
        path_params=("user_id",),
        summary="Permanently delete an instance user account",
        destructive=True,
    ),
    Route(
        name="delete_sso_user",
        domain="admin",
        http_method="DELETE",
        path="admin/users/{user_id}/sso",
        auth="admin",
        path_params=("user_id",),
        summary="Unlink a user’s SSO identity (force back to password login)",
        destructive=True,
    ),
    Route(
        name="deauth_user",
        domain="admin",
        http_method="POST",
        path="admin/users/{user_id}/deauth",
        auth="admin",
        path_params=("user_id",),
        summary="Force-logout a user (invalidate all sessions/security stamp)",
        destructive=True,
    ),
    Route(
        name="disable_user",
        domain="admin",
        http_method="POST",
        path="admin/users/{user_id}/disable",
        auth="admin",
        path_params=("user_id",),
        summary="Disable (lock) a user account instance-wide",
        destructive=True,
    ),
    Route(
        name="enable_user",
        domain="admin",
        http_method="POST",
        path="admin/users/{user_id}/enable",
        auth="admin",
        path_params=("user_id",),
        summary="Re-enable a disabled user account",
    ),
    Route(
        name="remove_2fa",
        domain="admin",
        http_method="POST",
        path="admin/users/{user_id}/remove-2fa",
        auth="admin",
        path_params=("user_id",),
        summary="Strip all 2FA methods from a user (admin recovery action)",
        destructive=True,
    ),
    Route(
        name="resend_user_invite",
        domain="admin",
        http_method="POST",
        path="admin/users/{user_id}/invite/resend",
        auth="admin",
        path_params=("user_id",),
        summary="Resend a pending registration invite email",
    ),
    Route(
        name="update_membership_type",
        domain="admin",
        http_method="POST",
        path="admin/users/org_type",
        auth="admin",
        summary="Change a user’s org role from the admin panel",
    ),
    Route(
        name="update_revision_users",
        domain="admin",
        http_method="POST",
        path="admin/users/update_revision",
        auth="admin",
        summary="Force a client-sync revision bump for one/many users",
    ),
    Route(
        name="admin_delete_organization",
        domain="admin",
        http_method="POST",
        path="admin/organizations/{org_id}/delete",
        auth="admin",
        path_params=("org_id",),
        summary="Permanently delete an organization and all its data",
        destructive=True,
    ),
    Route(
        name="get_diagnostics_config",
        domain="admin",
        http_method="GET",
        path="admin/diagnostics/config",
        auth="admin",
        summary="Get sanitized server config as JSON for diagnostics",
    ),
    Route(
        name="get_diagnostics_http",
        domain="admin",
        http_method="GET",
        path="admin/diagnostics/http",
        auth="admin",
        query_params=("code",),
        summary="Diagnostic HTTP echo/status-code test endpoint",
    ),
    Route(
        name="post_config",
        domain="admin",
        http_method="POST",
        path="admin/config",
        auth="admin",
        summary="Persist configuration overrides (the settings normally set via env vars)",
    ),
    Route(
        name="delete_config",
        domain="admin",
        http_method="POST",
        path="admin/config/delete",
        auth="admin",
        summary="Reset configuration overrides back to defaults",
        destructive=True,
    ),
    Route(
        name="backup_db",
        domain="admin",
        http_method="POST",
        path="admin/config/backup_db",
        auth="admin",
        summary="Trigger an on-demand database backup (sqlite only)",
    ),
    Route(
        name="icon_external",
        domain="icons",
        http_method="GET",
        path="icons/{host}/icon.png",
        auth="none",
        path_params=("host",),
        summary="Fetch/cache a site favicon by hostname from the internet",
    ),
    Route(
        name="icon_internal",
        domain="icons",
        http_method="GET",
        path="icons/{host}/icon.png",
        auth="none",
        path_params=("host",),
        summary="Serve a favicon from local cache without external fetch (used when icon fetching is disabled)",
    ),
    Route(
        name="ldap_import",
        domain="public",
        http_method="POST",
        path="api/public/organization/import",
        auth="none",
        summary="Bulk-provision/deprovision org members + groups from an external directory (SCIM/LDAP-style)",
    ),
    Route(
        name="get_settings_domains",
        domain="misc",
        http_method="GET",
        path="api/settings/domains",
        auth="user",
        summary="Get the user’s configured equivalent-domains list (for autofill matching)",
    ),
    Route(
        name="post_settings_domains",
        domain="misc",
        http_method="POST",
        path="api/settings/domains",
        auth="user",
        summary="Set equivalent-domains list",
    ),
    Route(
        name="put_settings_domains",
        domain="misc",
        http_method="PUT",
        path="api/settings/domains",
        auth="user",
        summary="Set equivalent-domains list (PUT alias)",
    ),
    Route(
        name="hibp_breach",
        domain="misc",
        http_method="GET",
        path="api/hibp/breach",
        auth="user",
        query_params=("username",),
        summary="Proxy a Have I Been Pwned breach lookup for a username",
    ),
    Route(
        name="alive",
        domain="misc",
        http_method="GET",
        path="api/alive",
        auth="none",
        summary="Liveness/health check (also verifies DB connectivity)",
    ),
    Route(
        name="now",
        domain="misc",
        http_method="GET",
        path="api/now",
        auth="none",
        summary="Return current server time",
    ),
    Route(
        name="version",
        domain="misc",
        http_method="GET",
        path="api/version",
        auth="none",
        summary="Return server version string",
    ),
    Route(
        name="get_api_webauthn",
        domain="misc",
        http_method="GET",
        path="api/webauthn",
        auth="user",
        summary="Stub empty passkey list (prevents client errors; Vaultwarden does not support WebAuthn passwordless login)",
    ),
    Route(
        name="config",
        domain="misc",
        http_method="GET",
        path="api/config",
        auth="none",
        summary="Return server config/feature-flags/environment URLs used by clients on startup",
    ),
)

_names = [_r.name for _r in ROUTES]
if len(_names) != len(set(_names)):
    _dupes = sorted({_n for _n in _names if _names.count(_n) > 1})
    raise AssertionError(f"duplicate route names in ROUTES: {_dupes}")
